baseURL = "https://enochboadu.netlify.app/"
languageCode = "en-us"
title = "My Educational Blog"
theme = "ananke" # CHANGED TO ANANKE
mainSections = ["posts"]

[params]
  description = "A blog about educational strategies."
  avatar = "/images/default_avatar.png"
