baseURL = "https://enochboadu.netlify.app/" # CORRECT THIS LINE
languageCode = "en-us"
title = "My Educational Blog"
theme = "stack"
mainSections = ["posts"]

[params]
  description = "A blog about educational strategies."
  avatar = "/images/default_avatar.png"
