backend:
  name: github
  repo: CoDeMan-CoDeMaN/edu-blog
  branch: main
  auth_scope: repo
  base_url: https://enochboadu.netlify.app
  auth_endpoint: /admin/callback

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
