backend:
  name: git-gateway # This is the key change! It uses Netlify's Git Gateway.
  branch: main
  identity_url: https://enochboadu.netlify.app/.netlify/identity # Explicitly point to your Netlify Identity endpoint
  gateway_url: https://enochboadu.netlify.app/.netlify/git # Explicitly point to your Netlify Git Gateway endpoint

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }