backend:
  name: git-gateway
  branch: main
  identity_url: https://enochboadu.netlify.app/.netlify/identity
  gateway_url: https://enochboadu.netlify.app/.netlify/git

publish_mode: editorial_workflow # <-- This is the added line

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }